### PR TITLE
added testimonies compartment

### PR DESCRIPTION
**Pull request by ChloeSAPage**
Added more images. Needs a little more styling I think but is pretty good. Going to have to be done while doing js i think

### CODE REVIEW

**Comment by ChloeSAPage** [comment]
image

**Review by Sebbybobbler — APPROVED** [review]
Amazing !! Haha!!

**Review by cnrdgrgry — APPROVED** [review]
Love bananananananaman

**Review by cnrdgrgry — COMMENTED** [review]
nice

**Pull request merged**
