### PR TITLE
HTML structure and basic CSS. Using placeholders for now, will update.

### PR DESCRIPTION
**Pull request by Sebbybobbler**

### CODE REVIEW

**Comment by Sebbybobbler** [comment]
BTW, I am just doing this pull request for the basic structure. AM going to continue to work on this and update placeholders to make it look snazzy :D

**Review by ChloeSAPage — APPROVED** [review]

**Review by cnrdgrgry — APPROVED** [review]
Need to remember we have to credit usage of images from Unsplash or where-ever folks as we're putting out in the public domain.

**Review by cnrdgrgry — APPROVED** [review]

**Comment by ChloeSAPage** [comment]
> Need to remember we have to credit usage of images from Unsplash or where-ever folks as we're putting out in the public domain.

how do we do that?

**Comment by cnrdgrgry** [comment]
As you click on the download - a pop-up **Say Thanks** crops up, gives you a little bit of text and linky to copy. just put it under the image somewherre

**Pull request merged**
